name: Test, Lint & Format CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Attempt to restore cached dependencies
        uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Build # Debug build
        run: cargo build --verbose
      - name: Test # Test profile configured as release build, for faster prop testing.
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -Dwarnings
      - name: Documentation
        run: cargo doc --no-deps --workspace
      - name: Format
        run: cargo fmt --all -- --check
      - name: Examples
        run: |
          cargo run --example basic_usage
          cargo run --example custom_alphabet
          cargo run --example cursor
          cargo run --example text_with_rank_support
